### ISSUE TITLE
【展开开收起 css 动画】

### ISSUE THREAD

**Issue by DaZhiZi** [DaZhiZi/note#13]
张开收起的 CSS 动画通常实现折叠面板或能展开和收起内容的其他界面元素。以下是一个简单的示例代码，可以通过点击按钮来切换元素的 `展开` 和 `收起` 状态：

HTML:
```html
<button class="toggle-btn">展开/收起</button>
<div class="content">
  <p>需要展开和收起的内容在这里</p>
</div>
```

CSS:
```css
.content {
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.5s ease-out;
}

.active {
  max-height: 1000px; /* 设置你希望展开后的高度 */
  transition: max-height 0.5s ease-in;
}
```

JavaScript:
```js
document.querySelector('.toggle-btn').addEventListener('click', function() {
  document.querySelector('.content').classList.toggle('active');
});
```

这段代码将会切换 `.content` 元素的 `max-height` ，由于 CSS `transition` 属性的作用，元素的高度将会以平滑的动画显示。
