### ISSUE TITLE
【css 动画】

### ISSUE THREAD

**Issue by DaZhiZi** [DaZhiZi/note#9]
.anim-positionkey {
    animation: position_key .7s linear 0s forwards;
    -webkit-animation: position_key .7s linear 0s forwards;
    -moz-animation: position_key .7s linear 0s forwards
}

Classname 为 anim-positionkey ，页面左侧和右侧元素，从外部往里水平移动到页面中，position_key 这个怎样实现

`position_key` 可能是一个动画的名称，它定义了一个使用CSS3动画的类 `.anim-positionkey`，这个类将元素在页面内进行水平移动。 

这个动画使用了 `animation` 和 `@keyframes` CSS属性，同时使用的还有 `-webkit-animation` 和 `-moz-animation`，这是为了兼容不同的浏览器。

下面是CSS代码的详细解释:

```CSS
.anim-positionkey {
  /* 使用 position_key 这个自定义动画 */
  animation: position_key .7s linear 0s forwards;
  -webkit-animation: position_key .7s linear 0s forwards; /* Safari 和 Chrome */
  -moz-animation: position_key .7s linear 0s forwards; /* Firefox */
}

/* 定义位置关键帧的动画 */
@keyframes position_key {
  /* 从用户定义的开始位置移动到中间位置 */
  0% {
    transform: translateX(-100%);
  }
  50% {
    transform: translateX(50%);
  }
  /* 移动到用户定义的结束位置 */
  100% {
    transform: translateX(0%);
  }
}

/* Safari 和 Chrome 用的关键帧动画 */
@-webkit-keyframes position_key {
  0% {
    -webkit-transform: translateX(-100%);
  }
  50% {
    -webkit-transform: translateX(50%);
  }
  100% {
    -webkit-transform: translateX(0%);
  }
}

/* Firefox 用的关键帧动画 */
@-moz-keyframes position_key {
  0% {
    -moz-transform: translateX(-100%);
  }
  50% {
    -moz-transform: translateX(50%);
  }
  100% {
    -moz-transform: translateX(0%);
  }
}
```

带有 `.anim-positionkey` 的 HTML 元素将在页面中水平移动，在动画持续时间内，从画面外转移到画面内。 在设定的线性时间内有在移动位置（第二个参数），然后停在那里不动（后面的 `forwards` 参数）。
